{% set name = "hop-client" %}
{% set version = "0.11.0" %}
{% set sha256 = "0e91b7f5c6d6c9c72403e18ae153d6391adb7deb1a4a170884f7ec01787eb411" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}
{% set python_min = python_min | default("3.6") %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hop-client-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - hop = hop.__main__:main

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - adc-streaming >=2.5.0
    - bson
    - dataclasses
    - fastavro >=1.4.0
    - pluggy >=0.11
    - setuptools
    - scramp
    - toml >=0.9.4
    - xmltodict >=0.9.0

test:
  requires:
    - pip
    - pytest >=5.0
    - pytest-console-scripts
  source_files:
    - tests
  commands:
    - python -m pip check
    - python -m pytest tests

about:
  home: https://github.com/scimma/hop-client
  doc_url: https://hop-client.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pub-sub client library for Multimessenger Astrophysics
  description: |
    hop-client is a client library to publish and subscribe messages to
    HOPSKOTCH, a scalable, high-throughput low-latency platform for handling
    real-time data feeds for MMA applications.

extra:
  recipe-maintainers:
    - cnweaver
    - adambrazier
    - mjuric
    - bfc5288
    - myNameIsPatrick
