{% set name = "hop-client" %}
{% set version = "0.9.0" %}
{% set sha256 = "88929f318e4205c649e806252d1d3fc9ad559e68b5cbea7755205d9590fcae55" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hop-client-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - hop = hop.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools-scm
  run:
    - python >=3.6
    - adc-streaming >=2.1.0
    - dataclasses
    - fastavro >=1.4.0
    - pluggy >=0.11
    - toml >=0.9.4
    - xmltodict >=0.9.0

test:
  requires:
    - pytest >=5.0
    - pytest-console-scripts
    - setuptools
  source_files:
    - tests
  commands:
    - python -m pytest tests

about:
  home: https://github.com/scimma/hop-client
  doc_url: https://hop-client.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A pub-sub client library for Multimessenger Astrophysics
  description: |
    hop-client is a client library to publish and subscribe messages to
    HOPSKOTCH, a scalable, high-throughput low-latency platform for handling
    real-time data feeds for MMA applications.

extra:
  recipe-maintainers:
    - cnweaver
    - adambrazier
    - mjuric
    - bfc5288
    - myNameIsPatrick
